### ISSUE TITLE
Ran into issue while running the suggested example

### ISSUE THREAD

**Issue by pupatel** [Wainberg/PsyOPS#2]
home/testing tools/PsyOPS$ python PsyOPS.py --GWAS-hit-file Howard_102_MDD.tsv --output-file PsyOPS_Clust2_MDD.tsv
Loaded 102 autosomal GWAS hits from Howard_102_MDD.tsv
TypeError: unhashable type: 'set'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "PsyOPS.py", line 118, in <module>
    alias_to_gene = alias_to_gene[alias_to_gene.isin(genes.gene)]
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/series.py", line 4698, in isin
    result = algorithms.isin(self, values)
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/algorithms.py", line 475, in isin
    return f(comps, values)
  File "pandas/_libs/hashtable_func_helper.pxi", line 454, in pandas._libs.hashtable.ismember_object
SystemError: <built-in method view of numpy.ndarray object at 0x7fb147995490> returned a result with an error set

**Comment by Wainberg** [comment]
Thanks for raising this issue - I was able to reproduce it with an old version of pandas. With old versions of pandas, [explode()](https://pandas.pydata.org/docs/reference/api/pandas.Series.explode.html) doesn't explode Series where the elements are sets. I've committed a fix.

**Comment by pupatel** [comment]
Thanks
